version: '3.8'

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: minitwitDb
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    ports:
      - "127.0.0.1:5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
