version: '3.8'
services:
  db:
    build:
      context: .
      dockerfile: ./minitwit.Infrastructure/Dockerfile.db
    container_name: minitwit-db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=minitwit
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data

  minitwit-api:
    build:
      context: .
      dockerfile: ./minitwit.Api/Dockerfile.api
    depends_on:
      - db
    ports:
      - "5000:8080"
    environment:
      - ASPNETCORE_URLS=https://+:8080
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/app/aspnetapp.pfx
      - ASPNETCORE_Kestrel__Certificates__Default__Password=yourpassword
      - ASPNETCORE_HTTPS_PORT=8080
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Host=db;Port=5432;Database=minitwit;Username=postgres;Password=postgres
      - NODE_TLS_REJECT_UNAUTHORIZED=0
      
  web:
    build:
      context: ./minitwit.Web
      dockerfile: Dockerfile.web
    container_name: minitwit-web
    depends_on:
      - minitwit-api
    environment:
    - PORT=3000
    - ApiBaseUrl=http://minitwit-api:8080
    env_file:
    - ./minitwit.Web/.env
    ports:
    - "8080:3000"
volumes:
  db-data:
